function(omnity_add_target target_name)
	add_library(${target_name} STATIC "")
	add_library(${PROJECT_NAME}::${target_name} ALIAS ${target_name})
	target_include_directories(${target_name} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/private")
	target_include_directories(${target_name} PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/public")
endfunction()